### ISSUE TITLE
Deno deployment failed

### ISSUE THREAD

**Issue by ToNyRANDRIAMANANTSOA** [leon-kfd/howdz-deno#1]
Thank you for this deno project.

I was trying to deploy it at [Deno deploy](https://deno.com/deploy) but facing this issue after some packages download:

`Error The deployment failed: HTTP status client error (404 Not Found) for url (https://deno.land/std@0.201.0/encoding/_yaml/loader/loader.ts)`

Could it be related to the project or its dependencies or specific to deno (the std module states however that it is not yet stable) ? 

By the way, I'm still exploring deno.

![image](https://github.com/leon-kfd/howdz-deno/assets/50623932/ad6874e7-a835-4f0d-8b34-d05631d66af1)

**Comment by leon-kfd** [comment]
Fixed, pull the lastest code.

Problem: https://github.com/ubersl0th/markdown/pull/18
Just need to replace the `markdown` package from this code: 
`import { Marked } from 'https://raw.githubusercontent.com/ubersl0th/markdown/master/mod.ts`

**Comment by ToNyRANDRIAMANANTSOA** [comment]
It's working fine now. Thank you.
